### ISSUE TITLE
Show if map is on trial

### ISSUE THREAD

**Issue by VenkSociety** [NBCommunity/Issues#18]

**Comment by Electronitus** [comment]
**Details:**
- Introduce a command to label a map as on trial, e.g. `/trial [map]` or `/zs set trial [true]`.
- `[Trial]` is shown next to maps on trial during the vote in a different colour, e.g. orange (`%n`, `%r` or `%t`).
- A custom message is shown when the round on a trial map ends, e.g. `Remember to /like or /dislike this map as it's on trial!`.
- Increase the probability of maps on trial appearing in the vote by a custom factor, e.g. 2.
