### ISSUE TITLE
Jump height MOTD does not work

### ISSUE THREAD

**Issue by Electronitus** [NBCommunity/Issues#30]
**Describe the bug.**
The only map in rotation that uses a custom jump height is `cutsman_stage`.
`/map motd jumpheight=3.2` does not change the jump height. 

**Which server?**
ZS.

**How to reproduce the bug:**
1. Connect to ZS.
2. Type `/load cutsman_stage`.
3. Type `/g cutsman_stage`.
4. Type `/map motd jumpheight=3.2`.
5. Notice that the jump height does not change.

**Comment by VenkSociety** [comment]
Fixed in NBCommunity/ZS-Server@ff735c6.
